apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: app
spec:
  containers:
  - name: myapp
    image: app:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000